name: Release
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Get version
        id: get-version
        run: |
          result=$(python get_version.py | tail -n 1)
          echo "::set-output name=version::$(result)"
      - name: Publish release
        uses: release-drafter/release-drafter@v5
        with:
          publish: true
          filter-by-commitish: true
          name: ${{ steps.get-version.outputs.version }}
          version: ${{ steps.get-version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
